'use strict';

const fs = require('fs');
const path = require('path');
const { execFile } = require('child_process');
const { promisify } = require('util');
const {
    getTenantHostname,
    getTenantAppScheme,
    getTenantBaseDomain,
} = require('./tenantUrls');

const execFileAsync = promisify(execFile);

const DATA_DIR = path.join(__dirname, '../../data/mobile-apps');
const REGISTRY_JSON = path.join(DATA_DIR, 'registry.json');
const TENANTS_DIR = path.join(DATA_DIR, 'tenants');
const MOBILE_SOURCE = path.join(__dirname, '../../billing_kalimasada_mobile');
const MANIFEST_REL = path.join('public', 'mobile-app');

function ensureDirs() {
    for (const d of [DATA_DIR, TENANTS_DIR, path.join(__dirname, '../../public/mobile-app')]) {
        if (!fs.existsSync(d)) fs.mkdirSync(d, { recursive: true });
    }
}

function loadRegistry() {
    ensureDirs();
    if (!fs.existsSync(REGISTRY_JSON)) {
        const empty = { tenants: {}, updated_at: null };
        fs.writeFileSync(REGISTRY_JSON, JSON.stringify(empty, null, 2), 'utf8');
        return empty;
    }
    try {
        return JSON.parse(fs.readFileSync(REGISTRY_JSON, 'utf8'));
    } catch (_) {
        return { tenants: {}, updated_at: null };
    }
}

function saveRegistry(registry) {
    ensureDirs();
    registry.updated_at = new Date().toISOString();
    fs.writeFileSync(REGISTRY_JSON, JSON.stringify(registry, null, 2), 'utf8');
    return registry;
}

function slugifyPackageId(subdomain) {
    const s = String(subdomain || 'tenant').toLowerCase().replace(/[^a-z0-9_]/g, '_');
    return `com.kalimasada.billing.${s}`;
}

function getTenantApiBaseUrl(subdomain) {
    const scheme = getTenantAppScheme();
    const host = getTenantHostname(subdomain);
    return `${scheme}://${host}`;
}

function getTenantWorkspaceDir(subdomain) {
    const slug = String(subdomain || '').toLowerCase().trim();
    return path.join(TENANTS_DIR, slug);
}

function getDefaultAppName(tenant) {
    const name = String(tenant?.name || tenant?.subdomain || 'Kalimasada').trim();
    return `${name} Mobile`;
}

function getTenantConfig(tenant) {
    const registry = loadRegistry();
    const sub = String(tenant.subdomain || '').toLowerCase();
    const stored = registry.tenants[sub] || {};
    return {
        tenantId: tenant.id,
        subdomain: sub,
        appName: stored.appName || getDefaultAppName(tenant),
        apiUrl: stored.apiUrl || getTenantApiBaseUrl(sub),
        packageId: stored.packageId || slugifyPackageId(sub),
        releaseNotes: stored.releaseNotes || '',
        updatedAt: stored.updatedAt || null,
        lastGeneratedAt: stored.lastGeneratedAt || null,
        lastBuildAt: stored.lastBuildAt || null,
        lastBuildStatus: stored.lastBuildStatus || null,
        lastBuildMessage: stored.lastBuildMessage || '',
        lastApkFile: stored.lastApkFile || null,
        workspaceDir: getTenantWorkspaceDir(sub),
    };
}

function saveTenantConfig(tenant, updates = {}) {
    const registry = loadRegistry();
    const sub = String(tenant.subdomain || '').toLowerCase();
    const current = getTenantConfig(tenant);
    const merged = {
        ...current,
        ...updates,
        tenantId: tenant.id,
        subdomain: sub,
        updatedAt: new Date().toISOString(),
    };
    registry.tenants[sub] = {
        tenantId: merged.tenantId,
        subdomain: merged.subdomain,
        appName: String(merged.appName || '').trim() || getDefaultAppName(tenant),
        apiUrl: String(merged.apiUrl || '').trim().replace(/\/+$/, '') || getTenantApiBaseUrl(sub),
        packageId: String(merged.packageId || '').trim() || slugifyPackageId(sub),
        releaseNotes: String(merged.releaseNotes || '').trim(),
        updatedAt: merged.updatedAt,
        lastGeneratedAt: merged.lastGeneratedAt,
        lastBuildAt: merged.lastBuildAt,
        lastBuildStatus: merged.lastBuildStatus,
        lastBuildMessage: merged.lastBuildMessage,
        lastApkFile: merged.lastApkFile,
    };
    saveRegistry(registry);
    return getTenantConfig(tenant);
}

function buildEnvContent(apiUrl) {
    const url = String(apiUrl || '').trim().replace(/\/+$/, '');
    return [
        '# Generated by Kalimasada Management — Mobile App Management',
        `# ${new Date().toISOString()}`,
        '',
        'API_URL=' + url,
        '',
        '# Pembaruan APK: GET {API_URL}/api/mobile-adapter/app-update/manifest',
        '',
    ].join('\n');
}

function buildAppConfigJson(cfg, tenant) {
    return {
        tenant_id: tenant.id,
        tenant_name: tenant.name,
        subdomain: cfg.subdomain,
        app_name: cfg.appName,
        api_url: cfg.apiUrl,
        package_id: cfg.packageId,
        hostname: getTenantHostname(cfg.subdomain),
        base_domain: getTenantBaseDomain(),
        generated_at: new Date().toISOString(),
    };
}

function buildShellScript(cfg) {
    const ws = getTenantWorkspaceDir(cfg.subdomain);
    const mobile = MOBILE_SOURCE;
    const root = path.join(__dirname, '../..');
    const appLabel = String(cfg.appName || 'Kalimasada Mobile').replace(/"/g, '\\"');
    return `#!/usr/bin/env bash
# Build APK tenant: ${cfg.subdomain}
# Jalankan di server yang sudah terinstall Flutter SDK
set -euo pipefail

export FLUTTER_HOME="/opt/flutter"
export ANDROID_HOME="/opt/android-sdk"
export ANDROID_SDK_ROOT="/opt/android-sdk"
export PATH="$FLUTTER_HOME/bin:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"

ROOT="${root}"
MOBILE="${mobile}"
WS="${ws}"
MANIFEST_DIR="$ROOT/public/mobile-app/${cfg.subdomain}"

if ! command -v flutter >/dev/null 2>&1; then
  echo "ERROR: Flutter SDK belum terinstall. Install Flutter lalu jalankan ulang."
  exit 1
fi

if [ ! -d "$MOBILE" ]; then
  echo "ERROR: Proyek Flutter tidak ditemukan: $MOBILE"
  exit 1
fi

MANIFEST_SRC="$MOBILE/android/app/src/main/AndroidManifest.xml"
MANIFEST_BAK="$WS/AndroidManifest.xml.bak"

mkdir -p "$WS/output" "$WS/logs" "$MANIFEST_DIR"

cp "$WS/.env" "$MOBILE/.env"
cp "$MANIFEST_SRC" "$MANIFEST_BAK"
sed -i 's/android:label="[^"]*"/android:label="${appLabel}"/' "$MANIFEST_SRC"

cd "$MOBILE"
echo "==> Bersihkan cache Gradle (hindari error createFullJarRelease)..."
(cd android && ./gradlew clean --no-build-cache) 2>&1 | tee "$WS/logs/last-build.log" || true
flutter pub get
flutter build apk --release 2>&1 | tee -a "$WS/logs/last-build.log"

APK_NAME="${cfg.subdomain}-mobile-$(date +%Y%m%d-%H%M).apk"
cp build/app/outputs/flutter-apk/app-release.apk "$WS/output/$APK_NAME"
cp "$WS/output/$APK_NAME" "$ROOT/public/mobile-app/${cfg.subdomain}/$APK_NAME"

mv "$MANIFEST_BAK" "$MANIFEST_SRC"

echo "OK: APK → $WS/output/$APK_NAME"
`;
}

function writeTenantManifest(cfg, apkFileName, version = '5.9.2', buildNumber = 91) {
    const manifestDir = path.join(__dirname, '../../public/mobile-app', cfg.subdomain);
    if (!fs.existsSync(manifestDir)) fs.mkdirSync(manifestDir, { recursive: true });
    const manifest = {
        version,
        build_number: buildNumber,
        apk_url: `/mobile-app/${cfg.subdomain}/${apkFileName}`,
        force_update: false,
        release_notes: cfg.releaseNotes || `Build ${cfg.appName} — tenant ${cfg.subdomain}`,
    };
    fs.writeFileSync(path.join(manifestDir, 'manifest.json'), JSON.stringify(manifest, null, 2), 'utf8');
    return manifest;
}

function generateWorkspace(tenant, overrides = {}) {
    const cfg = saveTenantConfig(tenant, overrides);
    const ws = getTenantWorkspaceDir(cfg.subdomain);
    const outputDir = path.join(ws, 'output');
    const logsDir = path.join(ws, 'logs');
    for (const d of [ws, outputDir, logsDir]) {
        if (!fs.existsSync(d)) fs.mkdirSync(d, { recursive: true });
    }

    fs.writeFileSync(path.join(ws, '.env'), buildEnvContent(cfg.apiUrl), 'utf8');
    fs.writeFileSync(path.join(ws, 'app-config.json'), JSON.stringify(buildAppConfigJson(cfg, tenant), null, 2), 'utf8');
    fs.writeFileSync(path.join(ws, 'build.sh'), buildShellScript(cfg), { mode: 0o755 });
    fs.writeFileSync(path.join(ws, 'README.txt'), [
        `Kalimasada Mobile — Tenant: ${cfg.subdomain}`,
        `App: ${cfg.appName}`,
        `API: ${cfg.apiUrl}`,
        '',
        'Struktur folder:',
        '  .env              → salin ke billing_kalimasada_mobile/.env saat build',
        '  app-config.json   → metadata build',
        '  build.sh          → script build APK (butuh Flutter SDK)',
        '  output/           → hasil APK',
        '  logs/             → log build terakhir',
        '',
        'Build manual:',
        `  bash ${ws}/build.sh`,
        '',
        'Atau dari Management Portal: tombol "Build APK".',
    ].join('\n'), 'utf8');

    saveTenantConfig(tenant, {
        lastGeneratedAt: new Date().toISOString(),
        lastBuildStatus: null,
        lastBuildMessage: 'Workspace config dihasilkan',
    });

    return { cfg: getTenantConfig(tenant), workspaceDir: ws };
}

async function getFlutterStatus() {
    try {
        const { stdout } = await execFileAsync('flutter', ['--version'], { timeout: 8000 });
        return { installed: true, version: (stdout || '').split('\n')[0].trim() };
    } catch (_) {
        return { installed: false, version: null };
    }
}

async function runBuild(tenant) {
    const cfg = getTenantConfig(tenant);
    generateWorkspace(tenant);

    const flutter = await getFlutterStatus();
    if (!flutter.installed) {
        const msg = 'Flutter SDK belum terinstall di server. Config & build.sh sudah dibuat — jalankan build.sh manual di mesin yang ada Flutter.';
        saveTenantConfig(tenant, {
            lastBuildAt: new Date().toISOString(),
            lastBuildStatus: 'pending',
            lastBuildMessage: msg,
        });
        return { ok: false, pending: true, message: msg, cfg: getTenantConfig(tenant) };
    }

    const ws = getTenantWorkspaceDir(cfg.subdomain);
    const buildScript = path.join(ws, 'build.sh');
    const logPath = path.join(ws, 'logs', 'last-build.log');

    try {
        const flutterBin = '/opt/flutter/bin';
        const androidHome = process.env.ANDROID_HOME || '/opt/android-sdk';
        const { stdout, stderr } = await execFileAsync('bash', [buildScript], {
            timeout: 20 * 60 * 1000,
            cwd: ws,
            env: {
                ...process.env,
                HOME: process.env.HOME || '/tmp',
                FLUTTER_HOME: process.env.FLUTTER_HOME || '/opt/flutter',
                ANDROID_HOME: androidHome,
                ANDROID_SDK_ROOT: process.env.ANDROID_SDK_ROOT || androidHome,
                PATH: `${flutterBin}:${androidHome}/cmdline-tools/latest/bin:${androidHome}/platform-tools:${process.env.PATH || ''}`,
            },
        });
        const log = `${stdout || ''}\n${stderr || ''}`.trim();
        fs.writeFileSync(logPath, log, 'utf8');

        const outputDir = path.join(ws, 'output');
        const apks = fs.readdirSync(outputDir).filter((f) => f.endsWith('.apk')).sort();
        const latestApk = apks[apks.length - 1] || null;

        if (latestApk) {
            writeTenantManifest(cfg, latestApk);
            saveTenantConfig(tenant, {
                lastBuildAt: new Date().toISOString(),
                lastBuildStatus: 'success',
                lastBuildMessage: `APK berhasil: ${latestApk}`,
                lastApkFile: latestApk,
            });
            return { ok: true, message: `Build sukses: ${latestApk}`, apk: latestApk, cfg: getTenantConfig(tenant) };
        }

        throw new Error('Build selesai tetapi file APK tidak ditemukan di output/');
    } catch (err) {
        const msg = (err.stderr || err.message || String(err)).trim();
        try { fs.writeFileSync(logPath, msg, 'utf8'); } catch (_) {}
        saveTenantConfig(tenant, {
            lastBuildAt: new Date().toISOString(),
            lastBuildStatus: 'failed',
            lastBuildMessage: msg.slice(0, 2000),
        });
        return { ok: false, message: msg, cfg: getTenantConfig(tenant) };
    }
}

function listTenantRows(tenants) {
    return (tenants || [])
        .filter((t) => t.subdomain && !String(t.subdomain).includes('__del_'))
        .map((t) => {
            const cfg = getTenantConfig(t);
            const ws = getTenantWorkspaceDir(t.subdomain);
            const hasWorkspace = fs.existsSync(path.join(ws, '.env'));
            const outputDir = path.join(ws, 'output');
            let apkCount = 0;
            if (fs.existsSync(outputDir)) {
                apkCount = fs.readdirSync(outputDir).filter((f) => f.endsWith('.apk')).length;
            }
            return {
                id: t.id,
                name: t.name,
                subdomain: t.subdomain,
                status: t.status,
                appName: cfg.appName,
                apiUrl: cfg.apiUrl,
                packageId: cfg.packageId,
                hasWorkspace,
                apkCount,
                lastBuildStatus: cfg.lastBuildStatus,
                lastBuildAt: cfg.lastBuildAt,
                lastApkFile: cfg.lastApkFile,
                workspaceDir: ws,
            };
        });
}

function getLatestApkPath(subdomain) {
    const ws = getTenantWorkspaceDir(subdomain);
    const outputDir = path.join(ws, 'output');
    if (!fs.existsSync(outputDir)) return null;
    const apks = fs.readdirSync(outputDir).filter((f) => f.endsWith('.apk')).sort();
    const latest = apks[apks.length - 1];
    return latest ? path.join(outputDir, latest) : null;
}

module.exports = {
    DATA_DIR,
    TENANTS_DIR,
    MOBILE_SOURCE,
    loadRegistry,
    getTenantApiBaseUrl,
    getTenantConfig,
    saveTenantConfig,
    generateWorkspace,
    runBuild,
    getFlutterStatus,
    listTenantRows,
    getLatestApkPath,
    getTenantWorkspaceDir,
    writeTenantManifest,
};
