#!/usr/bin/env bash
#
# install-freeradius-local-pop.sh
# Install FreeRADIUS lokal (Ubuntu/Debian) untuk POP — siap dipakai dengan
# Billing Kalimasada. File ini MANDIRI (tidak perlu clone repo penuh).
#
# Cara pakai (di PC Ubuntu site/POP):
#   chmod +x install-freeradius-local-pop.sh
#   sudo bash install-freeradius-local-pop.sh
#
# Atau non-interaktif:
#   sudo bash install-freeradius-local-pop.sh \
#     --pop-name "POP-BNA1" \
#     --nas-ip 192.168.10.1 \
#     --nas-secret 'RahasiaMikrotik'
#
# Opsi:
#   --mode sqlite|mysql   default: sqlite (paling sederhana untuk POP lokal)
#   --pop-name NAMA
#   --nas-ip IP           IP LAN MikroTik (client RADIUS)
#   --nas-secret SECRET   secret yang sama di MikroTik /radius
#   --radius-db PATH      default: /var/lib/freeradius/radius.db
#   --billing-host IP     IP tunnel VPS billing (catatan saja)
#   --yes                 jangan tanya konfirmasi
#
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; NC='\033[0m'

log_info()    { echo -e "${BLUE}[INFO]${NC} $*"; }
log_ok()      { echo -e "${GREEN}[OK]${NC} $*"; }
log_warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }

RADIUS_MODE="sqlite"
RADIUS_DB_PATH="/var/lib/freeradius/radius.db"
POP_NAME=""
NAS_IP=""
NAS_SECRET=""
BILLING_HOST=""
ASSUME_YES=0
FR_DIR="/etc/freeradius/3.0"
CLIENTS_CONF="${FR_DIR}/clients.conf"
SQL_ENABLED="${FR_DIR}/mods-enabled/sql"
INFO_DIR="/etc/freeradius/billing-pop"

require_root() {
  if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
    log_error "Jalankan dengan sudo: sudo bash $0"
    exit 1
  fi
}

usage() {
  sed -n '2,28p' "$0" | sed 's/^# \{0,1\}//'
  exit "${1:-0}"
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --mode) RADIUS_MODE="$2"; shift 2 ;;
      --pop-name) POP_NAME="$2"; shift 2 ;;
      --nas-ip) NAS_IP="$2"; shift 2 ;;
      --nas-secret) NAS_SECRET="$2"; shift 2 ;;
      --radius-db) RADIUS_DB_PATH="$2"; shift 2 ;;
      --billing-host) BILLING_HOST="$2"; shift 2 ;;
      --yes|-y) ASSUME_YES=1; shift ;;
      -h|--help) usage 0 ;;
      *) log_error "Opsi tidak dikenal: $1"; usage 1 ;;
    esac
  done
  case "$RADIUS_MODE" in
    sqlite|mysql) ;;
    *) log_error "--mode harus sqlite atau mysql"; exit 1 ;;
  esac
}

prompt_if_empty() {
  local var_name="$1" prompt="$2" default="${3:-}"
  local current="${!var_name}"
  if [[ -n $current ]]; then return 0; fi
  if [[ $ASSUME_YES -eq 1 ]]; then
    eval "$var_name=\"$default\""
    return 0
  fi
  if [[ -n $default ]]; then
    read -r -p "$prompt [$default]: " current
    current="${current:-$default}"
  else
    read -r -p "$prompt: " current
  fi
  eval "$var_name=\"$current\""
}

gen_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 18 | tr -d '/+=' | head -c 20
  else
    date +%s%N | sha256sum | head -c 20
  fi
}

detect_os() {
  # shellcheck disable=SC1091
  . /etc/os-release
  log_info "OS: ${ID:-?} ${VERSION_ID:-?}"
  if [[ "${ID:-}" != "ubuntu" && "${ID:-}" != "debian" ]]; then
    log_warn "Script diuji di Ubuntu/Debian — lanjut dengan risiko sendiri"
  fi
}

fr_svc() {
  if systemctl list-unit-files 2>/dev/null | grep -q '^freeradius\.service'; then
    echo freeradius
  else
    echo freeradius
  fi
}

install_packages() {
  export DEBIAN_FRONTEND=noninteractive
  log_info "Update apt & install paket FreeRADIUS ($RADIUS_MODE)..."
  apt-get update -qq
  if [[ "$RADIUS_MODE" == "mysql" ]]; then
    apt-get install -y freeradius freeradius-mysql freeradius-utils mariadb-server sqlite3
  else
    local pkgs=(freeradius freeradius-utils sqlite3)
    if apt-cache show freeradius-sqlite &>/dev/null; then
      pkgs+=(freeradius-sqlite)
    fi
    apt-get install -y "${pkgs[@]}"
  fi
  log_ok "Paket terpasang"
}

write_sql_module_sqlite() {
  mkdir -p "$(dirname "$RADIUS_DB_PATH")"
  touch "$RADIUS_DB_PATH"
  chown freerad:freerad "$(dirname "$RADIUS_DB_PATH")" 2>/dev/null || true
  chown freerad:freerad "$RADIUS_DB_PATH" 2>/dev/null || chmod 664 "$RADIUS_DB_PATH"

  find "${FR_DIR}/mods-enabled" -maxdepth 1 -type f \( -name '*.bak*' -o -name '*.backup*' -o -name '*~' \) -delete 2>/dev/null || true
  rm -f "$SQL_ENABLED"

  cat > "$SQL_ENABLED" <<EOF
# Generated by install-freeradius-local-pop.sh — $(date -Iseconds)
sql {
	dialect = "sqlite"
	driver = "rlm_sql_\${dialect}"

	sqlite {
		filename = "${RADIUS_DB_PATH}"
		busy_timeout = 60000
	}

	max_connections = 1

	acct_table1 = "radacct"
	acct_table2 = "radacct"
	postauth_table = "radpostauth"
	authcheck_table = "radcheck"
	groupcheck_table = "radgroupcheck"
	authreply_table = "radreply"
	groupreply_table = "radgroupreply"
	usergroup_table = "radusergroup"

	delete_stale_sessions = yes
	read_clients = yes
	client_table = "nas"
	group_attribute = "SQL-Group"

	\$INCLUDE \${modconfdir}/\${.:name}/main/\${dialect}/queries.conf
}
EOF
  chown freerad:freerad "$SQL_ENABLED"
  chmod 640 "$SQL_ENABLED"
  log_ok "Modul SQL SQLite → $RADIUS_DB_PATH"
}

init_sqlite_schema() {
  log_info "Inisialisasi schema SQLite RADIUS..."
  sqlite3 "$RADIUS_DB_PATH" <<'SQL'
CREATE TABLE IF NOT EXISTS nas (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nasname TEXT NOT NULL,
  shortname TEXT,
  type TEXT DEFAULT 'other',
  ports INTEGER,
  secret TEXT NOT NULL,
  server TEXT,
  community TEXT,
  description TEXT
);
CREATE TABLE IF NOT EXISTS radcheck (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL DEFAULT '',
  attribute TEXT NOT NULL DEFAULT '',
  op TEXT NOT NULL DEFAULT '==',
  value TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS radcheck_username ON radcheck(username);
CREATE UNIQUE INDEX IF NOT EXISTS radcheck_user_attr ON radcheck(username, attribute);
CREATE TABLE IF NOT EXISTS radreply (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL DEFAULT '',
  attribute TEXT NOT NULL DEFAULT '',
  op TEXT NOT NULL DEFAULT '=',
  value TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS radreply_username ON radreply(username);
CREATE TABLE IF NOT EXISTS radgroupcheck (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  groupname TEXT NOT NULL DEFAULT '',
  attribute TEXT NOT NULL DEFAULT '',
  op TEXT NOT NULL DEFAULT '==',
  value TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS radgroupreply (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  groupname TEXT NOT NULL DEFAULT '',
  attribute TEXT NOT NULL DEFAULT '',
  op TEXT NOT NULL DEFAULT '=',
  value TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS radusergroup (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL DEFAULT '',
  groupname TEXT NOT NULL DEFAULT '',
  priority INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS radusergroup_username ON radusergroup(username);
CREATE TABLE IF NOT EXISTS radacct (
  radacctid INTEGER PRIMARY KEY AUTOINCREMENT,
  acctsessionid TEXT NOT NULL DEFAULT '',
  acctuniqueid TEXT NOT NULL DEFAULT '',
  username TEXT NOT NULL DEFAULT '',
  realm TEXT,
  nasipaddress TEXT NOT NULL DEFAULT '',
  nasportid TEXT,
  nasporttype TEXT,
  acctstarttime TEXT,
  acctupdatetime TEXT,
  acctstoptime TEXT,
  acctsessiontime INTEGER,
  acctauthentic TEXT,
  connectinfo_start TEXT,
  connectinfo_stop TEXT,
  acctinputoctets INTEGER,
  acctoutputoctets INTEGER,
  calledstationid TEXT NOT NULL DEFAULT '',
  callingstationid TEXT NOT NULL DEFAULT '',
  acctterminatecause TEXT NOT NULL DEFAULT '',
  servicetype TEXT,
  framedprotocol TEXT,
  framedipaddress TEXT NOT NULL DEFAULT '',
  framedipv6address TEXT NOT NULL DEFAULT '',
  framedipv6prefix TEXT NOT NULL DEFAULT '',
  framedinterfaceid TEXT NOT NULL DEFAULT '',
  delegatedipv6prefix TEXT NOT NULL DEFAULT ''
);
CREATE UNIQUE INDEX IF NOT EXISTS radacct_acctuniqueid ON radacct(acctuniqueid);
CREATE TABLE IF NOT EXISTS radpostauth (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL DEFAULT '',
  pass TEXT NOT NULL DEFAULT '',
  reply TEXT NOT NULL DEFAULT '',
  authdate TEXT NOT NULL DEFAULT (datetime('now','localtime'))
);
SQL
  chown freerad:freerad "$RADIUS_DB_PATH"
  chmod 664 "$RADIUS_DB_PATH"
  log_ok "Schema SQLite siap"
}

setup_mysql() {
  local root_pw radius_pw
  radius_pw="$(gen_secret)"
  root_pw="$(gen_secret)"
  log_info "Setup MariaDB database radius..."
  systemctl enable --now mariadb >/dev/null 2>&1 || systemctl enable --now mysql >/dev/null 2>&1 || true
  mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '${root_pw}'; FLUSH PRIVILEGES;" 2>/dev/null || true
  mysql -u root -p"${root_pw}" -e "CREATE DATABASE IF NOT EXISTS radius CHARACTER SET utf8mb4;" 2>/dev/null \
    || mysql -e "CREATE DATABASE IF NOT EXISTS radius CHARACTER SET utf8mb4;"
  mysql -u root -p"${root_pw}" -e "CREATE USER IF NOT EXISTS 'radius'@'localhost' IDENTIFIED BY '${radius_pw}'; GRANT ALL ON radius.* TO 'radius'@'localhost'; FLUSH PRIVILEGES;" 2>/dev/null \
    || mysql -e "CREATE USER IF NOT EXISTS 'radius'@'localhost' IDENTIFIED BY '${radius_pw}'; GRANT ALL ON radius.* TO 'radius'@'localhost'; FLUSH PRIVILEGES;"

  local schema="${FR_DIR}/mods-config/sql/main/mysql/schema.sql"
  if [[ -f $schema ]]; then
    mysql -u root -p"${root_pw}" radius < "$schema" 2>/dev/null \
      || mysql radius < "$schema" 2>/dev/null || true
  fi

  cat > "$SQL_ENABLED" <<EOF
# Generated by install-freeradius-local-pop.sh — $(date -Iseconds)
sql {
	dialect = "mysql"
	driver = "rlm_sql_\${dialect}"
	server = "localhost"
	port = 3306
	login = "radius"
	password = "${radius_pw}"
	radius_db = "radius"
	mysql { warnings = auto }
	acct_table1 = "radacct"
	acct_table2 = "radacct"
	postauth_table = "radpostauth"
	authcheck_table = "radcheck"
	groupcheck_table = "radgroupcheck"
	authreply_table = "radreply"
	groupreply_table = "radgroupreply"
	usergroup_table = "radusergroup"
	delete_stale_sessions = yes
	read_clients = yes
	client_table = "nas"
	group_attribute = "SQL-Group"
	\$INCLUDE \${modconfdir}/\${.:name}/main/\${dialect}/queries.conf
}
EOF
  chown freerad:freerad "$SQL_ENABLED"
  chmod 640 "$SQL_ENABLED"
  find "${FR_DIR}/mods-enabled" -maxdepth 1 -type f \( -name '*.bak*' -o -name '*.backup*' \) -delete 2>/dev/null || true

  mkdir -p /root
  cat > /root/.freeradius_local_pop_credentials <<EOF
MARIADB_ROOT_PASSWORD="${root_pw}"
RADIUS_MYSQL_PASSWORD="${radius_pw}"
RADIUS_MYSQL_USER=radius
RADIUS_MYSQL_DATABASE=radius
EOF
  chmod 600 /root/.freeradius_local_pop_credentials
  export RADIUS_MYSQL_PASSWORD="$radius_pw"
  log_ok "MySQL radius siap (password di /root/.freeradius_local_pop_credentials)"
}

add_nas_client() {
  [[ -n $NAS_IP ]] || { log_warn "NAS IP kosong — lewati clients.conf"; return 0; }
  [[ -f $CLIENTS_CONF ]] || { log_error "clients.conf tidak ada"; return 1; }

  if grep -q "ipaddr = ${NAS_IP}" "$CLIENTS_CONF" 2>/dev/null; then
    log_info "NAS $NAS_IP sudah ada di clients.conf"
  else
    local cname="mikrotik-$(echo "$NAS_IP" | tr '.' '-')"
    cat >> "$CLIENTS_CONF" <<EOF

# Ditambahkan install-freeradius-local-pop.sh — $(date -Iseconds)
client ${cname} {
	ipaddr = ${NAS_IP}
	secret = ${NAS_SECRET}
	nas_type = other
	require_message_authenticator = no
}
EOF
    log_ok "NAS client ditambah: $NAS_IP"
  fi

  # Juga ke tabel nas (dibaca FR jika read_clients=yes)
  if [[ "$RADIUS_MODE" == "sqlite" && -f $RADIUS_DB_PATH ]]; then
    sqlite3 "$RADIUS_DB_PATH" \
      "INSERT INTO nas (nasname, shortname, type, secret, description)
       SELECT '${NAS_IP}', 'mikrotik-local', 'other', '${NAS_SECRET}', '${POP_NAME:-POP}';
       WHERE NOT EXISTS (SELECT 1 FROM nas WHERE nasname='${NAS_IP}');" 2>/dev/null || true
  elif [[ "$RADIUS_MODE" == "mysql" ]]; then
    mysql -u radius -p"${RADIUS_MYSQL_PASSWORD}" radius -e \
      "INSERT IGNORE INTO nas (nasname, shortname, type, secret, description)
       VALUES ('${NAS_IP}', 'mikrotik-local', 'other', '${NAS_SECRET}', '${POP_NAME:-POP}');" 2>/dev/null || true
  fi
}

tune_sites_light() {
  # Matikan post-auth berat jika ada — best effort, jangan gagalkan install
  local site="${FR_DIR}/sites-enabled/default"
  [[ -f $site ]] || return 0
  if grep -q 'Post-Auth-Type REJECT' "$site" 2>/dev/null; then
    log_info "Site default ada — biarkan; patch mass-auth opsional dari repo billing nanti"
  fi
}

open_firewall() {
  if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q 'Status: active'; then
    ufw allow 1812/udp comment 'RADIUS auth' >/dev/null 2>&1 || true
    ufw allow 1813/udp comment 'RADIUS acct' >/dev/null 2>&1 || true
    log_ok "UFW: 1812/1813 udp dibuka"
  else
    log_info "UFW tidak aktif — pastikan firewall mengizinkan UDP 1812/1813 dari MikroTik"
  fi
}

validate_and_start() {
  local svc
  svc="$(fr_svc)"
  if command -v freeradius >/dev/null 2>&1; then
    if freeradius -C >/dev/null 2>&1; then
      log_ok "Validasi config OK (freeradius -C)"
    else
      log_warn "freeradius -C mengeluh — cek log; tetap coba start"
      freeradius -C 2>&1 | tail -20 || true
    fi
  fi
  systemctl enable "$svc" >/dev/null 2>&1 || true
  systemctl restart "$svc"
  sleep 2
  if systemctl is-active --quiet "$svc"; then
    log_ok "FreeRADIUS aktif ($svc)"
  else
    log_error "FreeRADIUS gagal start — journalctl -u $svc -n 40"
    journalctl -u "$svc" -n 40 --no-pager || true
    exit 1
  fi
}

write_info() {
  mkdir -p "$INFO_DIR"
  local lan_ip
  lan_ip="$(hostname -I 2>/dev/null | awk '{print $1}' || echo 'IP_PC_INI')"
  cat > "${INFO_DIR}/pop-info.env" <<EOF
# $(date -Iseconds)
POP_NAME=${POP_NAME}
BILLING_HOST=${BILLING_HOST}
RADIUS_MODE=${RADIUS_MODE}
RADIUS_DB_PATH=${RADIUS_DB_PATH}
NAS_IP=${NAS_IP}
NAS_SECRET=${NAS_SECRET}
LAN_IP=${lan_ip}
AUTH_PORT=1812
ACCT_PORT=1813
EOF
  chmod 600 "${INFO_DIR}/pop-info.env"
  if [[ -n ${RADIUS_MYSQL_PASSWORD:-} ]]; then
    echo "RADIUS_MYSQL_PASSWORD=${RADIUS_MYSQL_PASSWORD}" >> "${INFO_DIR}/pop-info.env"
  fi
  log_ok "Info tersimpan: ${INFO_DIR}/pop-info.env"
}

print_done() {
  local lan_ip
  lan_ip="$(hostname -I 2>/dev/null | awk '{print $1}' || echo 'IP_LAN_PC_INI')"

  echo ""
  echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
  echo -e "${GREEN}║     FreeRADIUS lokal POP — install selesai                   ║${NC}"
  echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
  echo ""
  echo "  POP            : ${POP_NAME:-(-)}"
  echo "  IP LAN PC ini  : $lan_ip"
  echo "  Auth / Acct    : UDP 1812 / 1813"
  echo "  Mode           : $RADIUS_MODE"
  [[ "$RADIUS_MODE" == "sqlite" ]] && echo "  Database       : $RADIUS_DB_PATH"
  [[ "$RADIUS_MODE" == "mysql" ]] && echo "  MySQL creds    : /root/.freeradius_local_pop_credentials"
  echo "  NAS MikroTik   : ${NAS_IP:-(-)}  secret=${NAS_SECRET}"
  echo ""
  echo -e "${CYAN}1) Daftarkan di Management Portal (Radius Manager):${NC}"
  echo "   https://manage.kalimasada-app.com/management/pop/radius"
  echo "   Host     : (IP yang VPS bisa pantau — sering IP tunnel PC ini)"
  echo "   Auth/Acct: 1812 / 1813"
  echo "   Secret   : $NAS_SECRET"
  echo ""
  echo -e "${CYAN}2) Di MikroTik (JANGAN apply sebelum user sudah di-sync):${NC}"
  echo "   /radius add name=RADIUS-LOCAL address=${lan_ip} secret=${NAS_SECRET} service=ppp authentication-port=1812 accounting-port=1813 timeout=3s"
  echo "   /interface pppoe-server server set [find] authentication=radius"
  echo ""
  echo -e "${CYAN}3) Sync user dari billing VPS ke DB lokal ini dulu${NC}"
  echo "   (radcheck / radusergroup / radgroupreply) — baru cutover auth."
  echo ""
  echo -e "${CYAN}4) Cek lokal:${NC}"
  echo "   systemctl status freeradius"
  echo "   radtest TESTUSER TESTPASS 127.0.0.1 0 ${NAS_SECRET}"
  echo ""
}

main() {
  parse_args "$@"
  require_root
  detect_os

  echo ""
  echo -e "${GREEN}=== Install FreeRADIUS lokal POP (Kalimasada) ===${NC}"
  echo ""

  prompt_if_empty POP_NAME "Nama POP" "POP-LOKAL"
  prompt_if_empty NAS_IP "IP LAN MikroTik (NAS)" ""
  if [[ -z $NAS_SECRET ]]; then
    if [[ $ASSUME_YES -eq 1 ]]; then
      NAS_SECRET="$(gen_secret)"
    else
      read -r -p "Secret RADIUS (kosong = auto-generate): " NAS_SECRET
      [[ -n $NAS_SECRET ]] || NAS_SECRET="$(gen_secret)"
    fi
  fi
  prompt_if_empty BILLING_HOST "IP tunnel VPS billing (opsional)" ""

  if [[ $ASSUME_YES -ne 1 ]]; then
    echo ""
    echo "  Mode     : $RADIUS_MODE"
    echo "  POP      : $POP_NAME"
    echo "  NAS IP   : ${NAS_IP:-(belum diisi)}"
    echo "  Secret   : $NAS_SECRET"
    echo "  DB path  : $RADIUS_DB_PATH"
    echo ""
    read -r -p "Lanjut install? [y/N] " conf
    [[ "$conf" =~ ^[Yy]$ ]] || { log_warn "Dibatalkan"; exit 0; }
  fi

  install_packages

  if [[ "$RADIUS_MODE" == "mysql" ]]; then
    setup_mysql
  else
    write_sql_module_sqlite
    init_sqlite_schema
  fi

  add_nas_client
  tune_sites_light
  # Pin literal @ PPPoE usernames (same policy as VPS)
  _pin="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/freeradius-pin-literal-at.sh"
  if [[ -f $_pin ]]; then
    bash "$_pin" --no-restart
  else
    log_warn "freeradius-pin-literal-at.sh tidak ditemukan di samping installer — salin dari repo billing lalu: sudo bash freeradius-pin-literal-at.sh"
  fi
  open_firewall
  validate_and_start
  write_info
  print_done
}

main "$@"
